name: renovate

on:
  workflow_dispatch:
    branches:
      - master 
  schedule:
    - cron: "30 6 * * *"
  push:
    branches:
      - master 

jobs:
  renovate:
    runs-on: docker 
    container: ghcr.io/renovatebot/renovate:latest
    steps:
      - uses: actions/checkout@v6
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: ${{ forgejo.workspace }}/config.js
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
